-- Populate character mappings for transliteration
-- This migration adds comprehensive character mappings for supported scripts

-- Cyrillic to Latin mappings
INSERT INTO character_mappings (source_script, target_script, source_char, target_char, frequency_weight) VALUES
-- Vowels
('cyrillic', 'latin', 'а', 'a', 0.95),
('cyrillic', 'latin', 'А', 'A', 0.95, 'Basic vowel mapping (uppercase)'),
('cyrillic', 'latin', 'е', 'e', 0.95, 'Basic vowel mapping'),
('cyrillic', 'latin', 'Е', 'E', 0.95, 'Basic vowel mapping (uppercase)'),
('cyrillic', 'latin', 'ё', 'yo', 0.90, 'Diacritic vowel'),
('cyrillic', 'latin', 'Ё', 'Yo', 0.90, 'Diacritic vowel (uppercase)'),
('cyrillic', 'latin', 'и', 'i', 0.95, 'Basic vowel mapping'),
('cyrillic', 'latin', 'И', 'I', 0.95, 'Basic vowel mapping (uppercase)'),
('cyrillic', 'latin', 'о', 'o', 0.95, 'Basic vowel mapping'),
('cyrillic', 'latin', 'О', 'O', 0.95, 'Basic vowel mapping (uppercase)'),
('cyrillic', 'latin', 'у', 'u', 0.95, 'Basic vowel mapping'),
('cyrillic', 'latin', 'У', 'U', 0.95, 'Basic vowel mapping (uppercase)'),
('cyrillic', 'latin', 'ы', 'y', 0.85, 'Hard sign vowel'),
('cyrillic', 'latin', 'Ы', 'Y', 0.85, 'Hard sign vowel (uppercase)'),
('cyrillic', 'latin', 'э', 'e', 0.90, 'Reversed e'),
('cyrillic', 'latin', 'Э', 'E', 0.90, 'Reversed e (uppercase)'),
('cyrillic', 'latin', 'ю', 'yu', 0.90, 'Compound vowel'),
('cyrillic', 'latin', 'Ю', 'Yu', 0.90, 'Compound vowel (uppercase)'),
('cyrillic', 'latin', 'я', 'ya', 0.90, 'Compound vowel'),
('cyrillic', 'latin', 'Я', 'Ya', 0.90, 'Compound vowel (uppercase)'),

-- Consonants
('cyrillic', 'latin', 'б', 'b', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Б', 'B', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'в', 'v', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'В', 'V', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'г', 'g', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Г', 'G', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'д', 'd', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Д', 'D', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'ж', 'zh', 0.90, 'Fricative consonant'),
('cyrillic', 'latin', 'Ж', 'Zh', 0.90, 'Fricative consonant (uppercase)'),
('cyrillic', 'latin', 'з', 'z', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'З', 'Z', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'й', 'y', 0.90, 'Short i'),
('cyrillic', 'latin', 'Й', 'Y', 0.90, 'Short i (uppercase)'),
('cyrillic', 'latin', 'к', 'k', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'К', 'K', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'л', 'l', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Л', 'L', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'м', 'm', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'М', 'M', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'н', 'n', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Н', 'N', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'п', 'p', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'П', 'P', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'р', 'r', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Р', 'R', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'с', 's', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'С', 'S', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'т', 't', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Т', 'T', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'ф', 'f', 0.95, 'Basic consonant mapping'),
('cyrillic', 'latin', 'Ф', 'F', 0.95, 'Basic consonant mapping (uppercase)'),
('cyrillic', 'latin', 'х', 'kh', 0.85, 'Fricative consonant'),
('cyrillic', 'latin', 'Х', 'Kh', 0.85, 'Fricative consonant (uppercase)'),
('cyrillic', 'latin', 'ц', 'ts', 0.90, 'Affricate consonant'),
('cyrillic', 'latin', 'Ц', 'Ts', 0.90, 'Affricate consonant (uppercase)'),
('cyrillic', 'latin', 'ч', 'ch', 0.90, 'Affricate consonant'),
('cyrillic', 'latin', 'Ч', 'Ch', 0.90, 'Affricate consonant (uppercase)'),
('cyrillic', 'latin', 'ш', 'sh', 0.90, 'Fricative consonant'),
('cyrillic', 'latin', 'Ш', 'Sh', 0.90, 'Fricative consonant (uppercase)'),
('cyrillic', 'latin', 'щ', 'shch', 0.85, 'Complex fricative'),
('cyrillic', 'latin', 'Щ', 'Shch', 0.85, 'Complex fricative (uppercase)'),
('cyrillic', 'latin', 'ъ', '', 0.70, 'Hard sign (often omitted)'),
('cyrillic', 'latin', 'Ъ', '', 0.70, 'Hard sign (often omitted)'),
('cyrillic', 'latin', 'ь', '', 0.70, 'Soft sign (often omitted)'),
('cyrillic', 'latin', 'Ь', '', 0.70, 'Soft sign (often omitted)');

-- Chinese (simplified) to Latin mappings (basic Pinyin)
INSERT INTO character_mappings (source_script, target_script, source_char, target_char, frequency_weight) VALUES
('chinese', 'latin', '你', 'ni', 0.90, 'Common character: you'),
('chinese', 'latin', '好', 'hao', 0.90, 'Common character: good/well'),
('chinese', 'latin', '世', 'shi', 0.85, 'Common character: world'),
('chinese', 'latin', '界', 'jie', 0.85, 'Common character: boundary/world'),
('chinese', 'latin', '人', 'ren', 0.90, 'Common character: person'),
('chinese', 'latin', '大', 'da', 0.90, 'Common character: big'),
('chinese', 'latin', '小', 'xiao', 0.90, 'Common character: small'),
('chinese', 'latin', '中', 'zhong', 0.90, 'Common character: middle/China'),
('chinese', 'latin', '国', 'guo', 0.90, 'Common character: country'),
('chinese', 'latin', '家', 'jia', 0.90, 'Common character: home/family'),
('chinese', 'latin', '我', 'wo', 0.95, 'Common character: I/me'),
('chinese', 'latin', '是', 'shi', 0.90, 'Common character: to be'),
('chinese', 'latin', '的', 'de', 0.95, 'Common particle'),
('chinese', 'latin', '了', 'le', 0.90, 'Common particle'),
('chinese', 'latin', '在', 'zai', 0.90, 'Common preposition: at/in'),
('chinese', 'latin', '有', 'you', 0.90, 'Common verb: to have'),
('chinese', 'latin', '不', 'bu', 0.95, 'Common negation: not'),
('chinese', 'latin', '这', 'zhe', 0.90, 'Common pronoun: this'),
('chinese', 'latin', '个', 'ge', 0.95, 'Common measure word'),
('chinese', 'latin', '一', 'yi', 0.95, 'Number: one');

-- Greek to Latin mappings
INSERT INTO character_mappings (source_script, target_script, source_char, target_char, frequency_weight) VALUES
('greek', 'latin', 'α', 'a', 0.95, 'Basic vowel mapping'),
('greek', 'latin', 'Α', 'A', 0.95, 'Basic vowel mapping (uppercase)'),
('greek', 'latin', 'β', 'b', 0.95, 'Basic consonant mapping'),
('greek', 'latin', 'Β', 'B', 0.95, 'Basic consonant mapping (uppercase)'),
('greek', 'latin', 'γ', 'g', 0.90, 'Gamma'),
('greek', 'latin', 'Γ', 'G', 0.90, 'Gamma (uppercase)'),
('greek', 'latin', 'δ', 'd', 0.90, 'Delta'),
('greek', 'latin', 'Δ', 'D', 0.90, 'Delta (uppercase)'),
('greek', 'latin', 'ε', 'e', 0.95, 'Basic vowel mapping'),
('greek', 'latin', 'Ε', 'E', 0.95, 'Basic vowel mapping (uppercase)'),
('greek', 'latin', 'ζ', 'z', 0.90, 'Zeta'),
('greek', 'latin', 'Ζ', 'Z', 0.90, 'Zeta (uppercase)'),
('greek', 'latin', 'η', 'e', 0.85, 'Eta (long e)'),
('greek', 'latin', 'Η', 'E', 0.85, 'Eta (long e) (uppercase)'),
('greek', 'latin', 'θ', 'th', 0.85, 'Theta'),
('greek', 'latin', 'Θ', 'Th', 0.85, 'Theta (uppercase)'),
('greek', 'latin', 'ι', 'i', 0.95, 'Basic vowel mapping'),
('greek', 'latin', 'Ι', 'I', 0.95, 'Basic vowel mapping (uppercase)'),
('greek', 'latin', 'κ', 'k', 0.95, 'Kappa'),
('greek', 'latin', 'Κ', 'K', 0.95, 'Kappa (uppercase)'),
('greek', 'latin', 'λ', 'l', 0.95, 'Lambda'),
('greek', 'latin', 'Λ', 'L', 0.95, 'Lambda (uppercase)'),
('greek', 'latin', 'μ', 'm', 0.95, 'Mu'),
('greek', 'latin', 'Μ', 'M', 0.95, 'Mu (uppercase)'),
('greek', 'latin', 'ν', 'n', 0.95, 'Nu'),
('greek', 'latin', 'Ν', 'N', 0.95, 'Nu (uppercase)'),
('greek', 'latin', 'ξ', 'x', 0.85, 'Xi'),
('greek', 'latin', 'Ξ', 'X', 0.85, 'Xi (uppercase)'),
('greek', 'latin', 'ο', 'o', 0.95, 'Basic vowel mapping'),
('greek', 'latin', 'Ο', 'O', 0.95, 'Basic vowel mapping (uppercase)'),
('greek', 'latin', 'π', 'p', 0.95, 'Pi'),
('greek', 'latin', 'Π', 'P', 0.95, 'Pi (uppercase)'),
('greek', 'latin', 'ρ', 'r', 0.95, 'Rho'),
('greek', 'latin', 'Ρ', 'R', 0.95, 'Rho (uppercase)'),
('greek', 'latin', 'σ', 's', 0.95, 'Sigma'),
('greek', 'latin', 'Σ', 'S', 0.95, 'Sigma (uppercase)'),
('greek', 'latin', 'ς', 's', 0.95, 'Final sigma'),
('greek', 'latin', 'τ', 't', 0.95, 'Tau'),
('greek', 'latin', 'Τ', 'T', 0.95, 'Tau (uppercase)'),
('greek', 'latin', 'υ', 'y', 0.90, 'Upsilon'),
('greek', 'latin', 'Υ', 'Y', 0.90, 'Upsilon (uppercase)'),
('greek', 'latin', 'φ', 'f', 0.90, 'Phi'),
('greek', 'latin', 'Φ', 'F', 0.90, 'Phi (uppercase)'),
('greek', 'latin', 'χ', 'ch', 0.85, 'Chi'),
('greek', 'latin', 'Χ', 'Ch', 0.85, 'Chi (uppercase)'),
('greek', 'latin', 'ψ', 'ps', 0.85, 'Psi'),
('greek', 'latin', 'Ψ', 'Ps', 0.85, 'Psi (uppercase)'),
('greek', 'latin', 'ω', 'o', 0.85, 'Omega (long o)'),
('greek', 'latin', 'Ω', 'O', 0.85, 'Omega (long o) (uppercase)');

-- Arabic to Latin mappings (basic romanization)
INSERT INTO character_mappings (source_script, target_script, source_char, target_char, frequency_weight) VALUES
('arabic', 'latin', 'ا', 'a', 0.90, 'Alif'),
('arabic', 'latin', 'ب', 'b', 0.95, 'Ba'),
('arabic', 'latin', 'ت', 't', 0.95, 'Ta'),
('arabic', 'latin', 'ث', 'th', 0.85, 'Tha'),
('arabic', 'latin', 'ج', 'j', 0.90, 'Jim'),
('arabic', 'latin', 'ح', 'h', 0.80, 'Ha (pharyngeal)'),
('arabic', 'latin', 'خ', 'kh', 0.80, 'Kha'),
('arabic', 'latin', 'د', 'd', 0.95, 'Dal'),
('arabic', 'latin', 'ذ', 'dh', 0.85, 'Dhal'),
('arabic', 'latin', 'ر', 'r', 0.95, 'Ra'),
('arabic', 'latin', 'ز', 'z', 0.95, 'Zay'),
('arabic', 'latin', 'س', 's', 0.95, 'Sin'),
('arabic', 'latin', 'ش', 'sh', 0.90, 'Shin'),
('arabic', 'latin', 'ص', 's', 0.85, 'Sad (emphatic)'),
('arabic', 'latin', 'ض', 'd', 0.80, 'Dad (emphatic)'),
('arabic', 'latin', 'ط', 't', 0.85, 'Ta (emphatic)'),
('arabic', 'latin', 'ظ', 'z', 0.80, 'Za (emphatic)'),
('arabic', 'latin', 'ع', '', 0.60, 'Ayn (often omitted)'),
('arabic', 'latin', 'غ', 'gh', 0.75, 'Ghayn'),
('arabic', 'latin', 'ف', 'f', 0.95, 'Fa'),
('arabic', 'latin', 'ق', 'q', 0.85, 'Qaf'),
('arabic', 'latin', 'ك', 'k', 0.95, 'Kaf'),
('arabic', 'latin', 'ل', 'l', 0.95, 'Lam'),
('arabic', 'latin', 'م', 'm', 0.95, 'Mim'),
('arabic', 'latin', 'ن', 'n', 0.95, 'Nun'),
('arabic', 'latin', 'ه', 'h', 0.90, 'Ha'),
('arabic', 'latin', 'و', 'w', 0.85, 'Waw'),
('arabic', 'latin', 'ي', 'y', 0.85, 'Ya');

-- Latin to ASCII mappings (diacritic removal)
INSERT INTO character_mappings (source_script, target_script, source_char, target_char, frequency_weight) VALUES
('latin', 'ascii', 'à', 'a', 0.98, 'A with grave accent'),
('latin', 'ascii', 'á', 'a', 0.98, 'A with acute accent'),
('latin', 'ascii', 'â', 'a', 0.98, 'A with circumflex'),
('latin', 'ascii', 'ã', 'a', 0.98, 'A with tilde'),
('latin', 'ascii', 'ä', 'a', 0.98, 'A with diaeresis'),
('latin', 'ascii', 'å', 'a', 0.98, 'A with ring above'),
('latin', 'ascii', 'æ', 'ae', 0.95, 'AE ligature'),
('latin', 'ascii', 'À', 'A', 0.98, 'A with grave accent (uppercase)'),
('latin', 'ascii', 'Á', 'A', 0.98, 'A with acute accent (uppercase)'),
('latin', 'ascii', 'Â', 'A', 0.98, 'A with circumflex (uppercase)'),
('latin', 'ascii', 'Ã', 'A', 0.98, 'A with tilde (uppercase)'),
('latin', 'ascii', 'Ä', 'A', 0.98, 'A with diaeresis (uppercase)'),
('latin', 'ascii', 'Å', 'A', 0.98, 'A with ring above (uppercase)'),
('latin', 'ascii', 'Æ', 'AE', 0.95, 'AE ligature (uppercase)'),
('latin', 'ascii', 'è', 'e', 0.98, 'E with grave accent'),
('latin', 'ascii', 'é', 'e', 0.98, 'E with acute accent'),
('latin', 'ascii', 'ê', 'e', 0.98, 'E with circumflex'),
('latin', 'ascii', 'ë', 'e', 0.98, 'E with diaeresis'),
('latin', 'ascii', 'È', 'E', 0.98, 'E with grave accent (uppercase)'),
('latin', 'ascii', 'É', 'E', 0.98, 'E with acute accent (uppercase)'),
('latin', 'ascii', 'Ê', 'E', 0.98, 'E with circumflex (uppercase)'),
('latin', 'ascii', 'Ë', 'E', 0.98, 'E with diaeresis (uppercase)'),
('latin', 'ascii', 'ì', 'i', 0.98, 'I with grave accent'),
('latin', 'ascii', 'í', 'i', 0.98, 'I with acute accent'),
('latin', 'ascii', 'î', 'i', 0.98, 'I with circumflex'),
('latin', 'ascii', 'ï', 'i', 0.98, 'I with diaeresis'),
('latin', 'ascii', 'Ì', 'I', 0.98, 'I with grave accent (uppercase)'),
('latin', 'ascii', 'Í', 'I', 0.98, 'I with acute accent (uppercase)'),
('latin', 'ascii', 'Î', 'I', 0.98, 'I with circumflex (uppercase)'),
('latin', 'ascii', 'Ï', 'I', 0.98, 'I with diaeresis (uppercase)'),
('latin', 'ascii', 'ò', 'o', 0.98, 'O with grave accent'),
('latin', 'ascii', 'ó', 'o', 0.98, 'O with acute accent'),
('latin', 'ascii', 'ô', 'o', 0.98, 'O with circumflex'),
('latin', 'ascii', 'õ', 'o', 0.98, 'O with tilde'),
('latin', 'ascii', 'ö', 'o', 0.98, 'O with diaeresis'),
('latin', 'ascii', 'ø', 'o', 0.95, 'O with stroke'),
('latin', 'ascii', 'œ', 'oe', 0.95, 'OE ligature'),
('latin', 'ascii', 'Ò', 'O', 0.98, 'O with grave accent (uppercase)'),
('latin', 'ascii', 'Ó', 'O', 0.98, 'O with acute accent (uppercase)'),
('latin', 'ascii', 'Ô', 'O', 0.98, 'O with circumflex (uppercase)'),
('latin', 'ascii', 'Õ', 'O', 0.98, 'O with tilde (uppercase)'),
('latin', 'ascii', 'Ö', 'O', 0.98, 'O with diaeresis (uppercase)'),
('latin', 'ascii', 'Ø', 'O', 0.95, 'O with stroke (uppercase)'),
('latin', 'ascii', 'Œ', 'OE', 0.95, 'OE ligature (uppercase)'),
('latin', 'ascii', 'ù', 'u', 0.98, 'U with grave accent'),
('latin', 'ascii', 'ú', 'u', 0.98, 'U with acute accent'),
('latin', 'ascii', 'û', 'u', 0.98, 'U with circumflex'),
('latin', 'ascii', 'ü', 'u', 0.98, 'U with diaeresis'),
('latin', 'ascii', 'Ù', 'U', 0.98, 'U with grave accent (uppercase)'),
('latin', 'ascii', 'Ú', 'U', 0.98, 'U with acute accent (uppercase)'),
('latin', 'ascii', 'Û', 'U', 0.98, 'U with circumflex (uppercase)'),
('latin', 'ascii', 'Ü', 'U', 0.98, 'U with diaeresis (uppercase)'),
('latin', 'ascii', 'ý', 'y', 0.98, 'Y with acute accent'),
('latin', 'ascii', 'ÿ', 'y', 0.98, 'Y with diaeresis'),
('latin', 'ascii', 'Ý', 'Y', 0.98, 'Y with acute accent (uppercase)'),
('latin', 'ascii', 'Ÿ', 'Y', 0.98, 'Y with diaeresis (uppercase)'),
('latin', 'ascii', 'ç', 'c', 0.98, 'C with cedilla'),
('latin', 'ascii', 'Ç', 'C', 0.98, 'C with cedilla (uppercase)'),
('latin', 'ascii', 'ñ', 'n', 0.98, 'N with tilde'),
('latin', 'ascii', 'Ñ', 'N', 0.98, 'N with tilde (uppercase)'),
('latin', 'ascii', 'ß', 'ss', 0.95, 'German eszett');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_character_mappings_input_output_script ON character_mappings(input_script, output_script);
CREATE INDEX IF NOT EXISTS idx_character_mappings_input_char ON character_mappings(input_char);
CREATE INDEX IF NOT EXISTS idx_character_mappings_confidence ON character_mappings(confidence_weight DESC);